name: Test Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x

      - name: Test
        with:
          working-directory: src
        run: dotnet test -c Release

      - name: Build & Pack
        run: dotnet pack src/ServerVariables/ServerVariables.csproj -c Release
